### ISSUE TITLE
The Extractinator/Numismatic Overhaul

### ISSUE THREAD

**Issue by JinxTheGoblin** [JustFoxx/Adventures-Of-Fox-Beginning-Of-A-Journey#2]
I think that adding The Extractinator and Numismatic Overhaul would make early game a bit more bearable and more fun

- The Extractinator would make it so you can get rid of junk blocks by turning them into valuable items

- The Numismatic Overhaul mod would allow for a more fun and immersive way of trading with villagers

- Also, The Extractinator mod has built-in compatibility with a lot of the mods in the pack as well as Numismatic Overhaul

Mod Links:
1. https://www.curseforge.com/minecraft/mc-mods/the-extractinator
2. https://www.curseforge.com/minecraft/mc-mods/numismatic-overhaul

**Comment by JustFoxx** [comment]
never knew about those mods, thanks for saying about them, i will see if i will add them to modpack

**Comment by JustFoxx** [comment]
problem with that first mod is, it's tech mod and i want make modpack to be fully rpg/exploration but the last one looks good

**Comment by JinxTheGoblin** [comment]
No problem! They seemed like great fits for the pack

BTW with the Subterrestrial mod the main chest gets replaced by the Extractinator

**Comment by JustFoxx** [comment]
Yeah subterrestrial is in modpack

**Comment by JustFoxx** [comment]
Check out update: https://github.com/JustFoxx/Adventures-Of-Fox-Beginning-Of-A-Journey/releases/tag/a0.4.2
